skip_docs

default_platform :mac

platform :mac do
  lane :deploy do
    installer_cert_name = ENV.fetch('FASTLANE_MAS_INSTALLER_CERT')

    build_app(
        scheme: 'Runner',
        configuration: 'Release',
        output_directory: '../../output',
        export_options: {
          method: 'app-store',
          provisioningProfiles: {
            'net.yuandev.onexray' => 'OneXraymacOS',
            'net.yuandev.onexray.tun' => 'OneXrayTunmacOS'
          }
        },
        installer_cert_name: installer_cert_name
    )
    api_key = app_store_connect_api_key(
      key_id: ENV.fetch('FASTLANE_ASC_KEY_ID'),
      issuer_id: ENV.fetch('FASTLANE_ASC_ISSUER_ID'),
      key_filepath: './fastlane/AuthKey.p8'
    )
    upload_to_testflight(
      api_key: api_key
    )
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
